# This file will contains every data used 
# to configure the tests.

SPI_FREQ : 9e6
REF_FREQ : 1e6
LAUNCH_CONFIG :
  single_test : 
    bool : 0
    test_file : "test1" 
  all_tests :  # Without IGNORED_TEST_FILE
    bool : 1
    ignored_test_files : 
      - .ipynb_checkpoints
      - test_zero_data.txt
  activate_exceptions : 0 #choose 1 to activate exceptions when an error occurs and 0 to desactivate it
  
TEST_FILE :
  nb_hex_per_packet : 8
  
RESULT_FILE : 
  name : "test1" # don't forget to change this if you want to keep previous results
  title_color : "rgb(0, 153, 255)"
  text_colors :
    default_color : "rgb(230, 230, 230)"
    error_color : "rgb(255, 255, 255)"
    validation_color : "rgb(255, 255, 255)"
  highlight_colors :
    error_color : "rgb(255, 0, 0)"
    validation_color : "rgb(0, 179, 0)"
    
STYLE_RESULT_FILE : "style.css"
CHOSEN_PLATFORM : PYNQ
PLATFORMS : 
  - name : PYNQ
    SPI_CLK : #TO DO
    MISO : #TO DO
    MOSI : #TO DO
    SS : #TO DO
  - name : RPi 
    MAX_SPEED_HZ : 5000
    MODE : 1 # SPI mode as two bit pattern of clock polarity and phase [CPOL|CPHA], min: 0b00 = 0, max: 0b11 = 3
  - name : virtual
