# This file will contains every data used 
# to configure the tests.

SPI_FREQ : 9e6
REF_FREQ : 1e6
LAUNCH_CONFIG : # single test and all test config cannot be used both at the same time
  single_test : 
    bool : 0
    test_file : "test1" 
  all_tests :  # Without IGNORED_TEST_FILE
    bool : 1
    ignored_test_files : 
      - .ipynb_checkpoints
  activate_exceptions : 0 #choose 1 to activate exceptions when an error occurs and 0 to desactivate it
  
TEST_FILE :
  nb_hex_per_packet : 8
  
RESULT_FILE : # print_msg, txt_config and html_onfig can all be used at the same time 
  print_msg : # once activated : prints every message from the functions in messages.ipynb : try not to use it in all tests config : output could be long ...
    bool : 0
  txt_config :
    bool : 1
  html_config :
    bool : 1
    title_color : "rgb(0, 153, 255)"
    text_colors :
      default_color : "rgb(230, 230, 230)"
      error_color : "rgb(255, 255, 255)"
      validation_color : "rgb(255, 255, 255)"
    highlight_colors :
      error_color : "rgb(255, 0, 0)"
      validation_color : "rgb(0, 179, 0)"
    
STYLE_RESULT_FILE : "style.css"
CHOSEN_PLATFORM : PYNQ
PLATFORMS : 
  - name : PYNQ
    SPI_CLK : #TO DO
    MISO : #TO DO
    MOSI : #TO DO
    SS : #TO DO
  - name : RPi 
    MAX_SPEED_HZ : 5000
    MODE : 1 # SPI mode as two bit pattern of clock polarity and phase [CPOL|CPHA], min: 0b00 = 0, max: 0b11 = 3
  - name : virtual
