# This file will contains every data used 
# to configure the tests.

LAUNCH_CONFIG : # single test and all test config cannot be used both at the same time
  single_test : 
    activate : 1
    test_file : "my_test" 
  all_tests :  # Without IGNORED_TEST_FILES
    activate : 0
    ignored_test_files : 
      - .ipynb_checkpoints  # don't remove this one
  max_while_iterations : 1000
  activate_exceptions : 0 #choose 1 to activate exceptions when an error occurs and 0 to desactivate it
  
  
  
RESULT_FILE : # print_msg, txt_config and html_onfig can all be used at the same time 
  print_msg : # once activated : prints every message from the functions in messages.ipynb : try not to 
              # use it in "all_tests" config : output could be long ...
    activate : 1
  txt_config :
    activate : 1
  html_config :
    activate : 1
    
STYLE_RESULT_FILE : "style.css"



HARDWARE:
  CHOSEN_PLATFORM : PYNQ
  PLATFORMS : 
    - name : PYNQ
    - SPI_FREQ : 9e6 # TO DO 
    - name : RPi 
      MAX_SPEED_HZ : 5000
      MODE : 1 # SPI mode as two bit pattern of clock polarity and phase [CPOL|CPHA], so 4 modes :[0;3]
    - name : virtual
    
  
            
