print_msg : 
  red_color : "rgb(255, 85, 85)"
  green_color : "rgb(0, 128, 0)"
  

html_config :
  title_color : "rgb(0, 153, 255)"
  text_colors :
    default_color : "rgb(230, 230, 230)"
    error_color : "rgb(255, 255, 255)"
    validation_color : "rgb(255, 255, 255)"
  highlight_colors :
    error_color : "rgb(255, 0, 0)"
    validation_color : "rgb(0, 179, 0)"


